name: Build Jekyll site
on:
 pull_request:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
           retention-days: 14
   link:
     needs: build # make sure the artifacts are uploaded first
     permissions:
        contents: write # for commenting on your commit
        pull-requests: write # for commenting on your pr
     steps:
       - uses: beni69/artifact-link@v1
         with:
           token: ${{ github.token }}

